-- Corporate Cab Service - reference schema
-- Note: In the actual app, this schema is generated by EF Core migrations
-- (`dotnet ef migrations add Initial` then `dotnet ef database update`).
-- This file is included for readability / direct DB inspection.

CREATE DATABASE CabServiceDb;
GO
USE CabServiceDb;
GO

CREATE TABLE Employees (
    EmployeeId INT IDENTITY PRIMARY KEY,
    FullName NVARCHAR(100) NOT NULL,
    Username NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    Department NVARCHAR(100) NOT NULL,
    Role NVARCHAR(20) NOT NULL,          -- Admin | Employee | Driver
    PhoneNumber NVARCHAR(20),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Vehicles (
    VehicleId INT IDENTITY PRIMARY KEY,
    RegistrationNumber NVARCHAR(20) NOT NULL UNIQUE,
    Make NVARCHAR(50) NOT NULL,
    Model NVARCHAR(50) NOT NULL,
    SeatingCapacity INT NOT NULL,
    Status NVARCHAR(20) NOT NULL,         -- Available | Assigned | Maintenance
    DriverId INT NULL REFERENCES Employees(EmployeeId)
);

CREATE TABLE VehicleRequests (
    RequestId INT IDENTITY PRIMARY KEY,
    EmployeeId INT NOT NULL REFERENCES Employees(EmployeeId),
    Purpose NVARCHAR(200) NOT NULL,
    RequiredFrom DATETIME2 NOT NULL,
    RequiredTo DATETIME2 NOT NULL,
    PickupLocation NVARCHAR(200) NOT NULL,
    DropLocation NVARCHAR(200) NOT NULL,
    Status NVARCHAR(20) NOT NULL,          -- Pending | Approved | Rejected | Completed
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    VehicleId INT NULL REFERENCES Vehicles(VehicleId)
);

CREATE TABLE AssignedVehicles (
    AssignmentId INT IDENTITY PRIMARY KEY,
    RequestId INT NOT NULL UNIQUE REFERENCES VehicleRequests(RequestId),
    VehicleId INT NOT NULL REFERENCES Vehicles(VehicleId),
    DriverId INT NULL REFERENCES Employees(EmployeeId),
    AssignedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    AssignedByAdminUsername NVARCHAR(100) NOT NULL
);

CREATE TABLE FuelLogs (
    FuelLogId INT IDENTITY PRIMARY KEY,
    VehicleId INT NOT NULL REFERENCES Vehicles(VehicleId),
    DriverId INT NOT NULL REFERENCES Employees(EmployeeId),
    LogDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FuelQuantityLiters DECIMAL(8,2) NOT NULL,
    Cost DECIMAL(10,2) NOT NULL,
    OdometerReading INT NOT NULL,
    Notes NVARCHAR(300)
);

CREATE TABLE FeedbackEntries (
    FeedbackId INT IDENTITY PRIMARY KEY,
    EmployeeId INT NOT NULL REFERENCES Employees(EmployeeId),
    VehicleId INT NOT NULL REFERENCES Vehicles(VehicleId),
    Rating INT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
    Comments NVARCHAR(500),
    SubmittedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE VehicleInsurances (
    InsuranceId INT IDENTITY PRIMARY KEY,
    VehicleId INT NOT NULL UNIQUE REFERENCES Vehicles(VehicleId),
    PolicyNumber NVARCHAR(50) NOT NULL,
    Provider NVARCHAR(100) NOT NULL,
    ValidFrom DATETIME2 NOT NULL,
    ValidTo DATETIME2 NOT NULL
);
